#pragma config(Motor,  port3,           driveL3,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveR2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveL1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           driveR1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveL2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveR3,       tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main{
  int lPow, rPow;

  while (true){

    lPow = vexRT[Ch3];
    rPow = vexRT[Ch2];

    motor[driveL1] = lPow;
  	motor[driveL2] = lPow;
  	motor[driveL3] = lPow;

  	motor[driveR1]  = rPow;
  	motor[driveR2]  = rPow;
  	motor[driveR3]  = rPow;

    wait1Msec(20);
  }
}
