#pragma config(Motor,  port2,           M_L1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           M_L2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           M_R1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           M_R2,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

		motor[M_L1] = -127;
		//motor[M_L2] = 127;
		motor[M_R1] = -127;
	//	motor[M_R2] = 127;
		delay(800);
		motor[M_L1] = 0;
		//motor[M_L2] = 0;
		motor[M_R1] = 0;
		//motor[M_R2] = 0;



}
