#pragma config(Sensor, dgtl1,  SOL_1,          sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	for(int i = 0; i < 10; i++)
	{
		SensorValue[SOL_1] = 1;
		sleep(5000);
		SensorValue[SOL_1] = 0;
		sleep(5000);
	}
}
