#pragma config(UserModel, "ports.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("vexCompetitionControl");
#pragma debuggerWindows("VexLCD");

//Main competition background code...do not modify!
// #include "Vex_Competition_Includes.c"
#warning "skills"
#include "vex.c"
#include "declarations.c"
#include "variablesForKent.c"
#include "functions.c"

///////////////////////////////////////////////////////////////////////////////////
// PRE AUTON
///////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	clearDebugStream();
	//startTask(autonomous);

	#include "pre_auton.c"
}//END pre_auton

///////////////////////////////////////////////////////////////////////////////////
// AUTONOMOUS
///////////////////////////////////////////////////////////////////////////////////

// skills - blue side facing mogo
task autonomous(){
	writeDebugStreamLine("auton - skills");

	startingRotationOffset = 0; // facing positive x towards mogo
  SensorValue[claw] = CLAW_CLOSE;
  setArmHeight(ARM_SCHMEDIUM);
	gyroPID.target 		= 0;
	startTask(armPIDTask);
	startTask(drivePIDTask);

	motor[mogo] = -127;
	wait1Msec(400); // 400
	driveIncremental(24); // forward 36 inches
	extendMogo();
	waitForPID(drivePID);
	tardDriveStraight(40);
	wait1Msec(500);
	tardDriveStraight();
	intakeMogo();

	driveIncremental(-15);
	waitForPID(drivePID);
	pointTurn(90);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);
	pointTurn(180);
	waitForPID(gyroPID);
	tardDriveStraight(127);
	wait1Msec(2000);
	tardDrive();

	extendMogo();
	driveIncremental(-4);
	waitForPID(drivePID);
	intakeMogo();

	driveIncremental(-17);
	waitForPID(drivePID);
	pointTurn(270);
	waitForPID(gyroPID);
	driveIncremental(20);
	waitForPID(drivePID);
	pointTurn(360);
	waitForPID(gyroPID);

	//2nd mogo
	motor[mogo] = -127;
	wait1Msec(400); // 400
	driveIncremental(24); // forward 36 inches
	extendMogo();
	waitForPID(drivePID);
	tardDriveStraight(40);
	wait1Msec(500);
	tardDriveStraight();
	intakeMogo();

	pointTurn(180);
	waitForPID(gyroPID);
	driveIncremental(24);
	waitForPID(drivePID);

	extendMogo();
	driveIncremental(-4);
	waitForPID(drivePID);
	intakeMogo();

	driveIncremental(-6);
	waitForPID(drivePID);
	pointTurn(360);
	waitForPID(gyroPID);

	//3rd mogo
	motor[mogo] = -127;
	wait1Msec(400); // 400
	driveIncremental(40); // forward 36 inches
	extendMogo();
	waitForPID(drivePID);
	tardDriveStraight(40);
	wait1Msec(500);
	tardDriveStraight();
	intakeMogo();
	driveIncremental(30);

	extendMogo();
	driveIncremental(-4);
	waitForPID(drivePID);
	intakeMogo();

	//4th mogo
	driveIncremental(-6);
	waitForPID(drivePID);
	pointTurn(450);
	waitForPID(gyroPID);
	driveIncremental(30);
	waitForPID(drivePID);
	pointTurn(540);
	waitForPID(gyroPID);

	motor[mogo] = -127;
	wait1Msec(400); // 400
	driveIncremental(24); // forward 36 inches
	extendMogo();
	waitForPID(drivePID);
	tardDriveStraight(40);
	wait1Msec(500);
	tardDriveStraight();
	intakeMogo();

	driveIncremental(-15);
	waitForPID(drivePID);
	pointTurn(450);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);
	pointTurn(360);
	waitForPID(gyroPID);
	tardDriveStraight(127);
	wait1Msec(2000);
	tardDrive();

	extendMogo();
	driveIncremental(-4);
	waitForPID(drivePID);
	intakeMogo();



	/////////////////////////////////////////////////////////
	// motor[mogo] = -127;
  // wait1Msec(400); // 400
  // driveIncremental(30); // forward 36 inches
  // extendMogo();
  // waitForPID(drivePID);
	// tardDriveStraight(40);
  // wait1Msec(500);
  // tardDriveStraight();
  // intakeMogo();
  //
	// driveIncremental(72);
  //
	// pointTurn(90);
	// waitForPID(gyroPID);
	// driveIncremental(-12);
	// waitForPID(drivePID);
	// pointTurn(0);
	// waitForPID(gyroPID);
	// tardDrive(127);
	// wait1Msec(1000);
	// tardDrive();
  //
	// extendMogo();
	// tardDriveStraight(-60);
	// wait1Msec(500);
	// intakeMogo();
	/////////////////////////////////////////////////////////



	// extendMogo();
	// tankDrive(127,127);
	// wait1Msec(1000);
	// tankDrive(0,0);
	// intakeMogo();
	// wait1Msec(500);
	// tankDrive(-127, 127);
	// wait1Msec(1700);
	// tankDrive(127,127);
	// wait1Msec(3000);
	// extendMogo();
	// tankDrive(-60, -60);
  //
  //
	// while(true){wait1Msec(1000);}
  //
	// clearTimer(T1);
	// startTask(displayTime);
	// int oldDrive;
	// SensorValue[driveREnc] = 0;//zero encoders
	// SensorValue[driveLEnc] = 0;
	// startingRotationOffset = 0; // facing positive x towards mogo
  //
	// SensorValue[claw] = CLAW_CLOSE;
	// armPID.target 		= ARM_SCHMEDIUM;
	// gyroPID.target 		= 0;
	// swingPID.target 	= SWING_IN;
	// startTask(armPIDTask);
	// startTask(drivePIDTask);
	// startTask(swingPIDTask);
  //
	// // mogo 1 - 20 pt blue
	// //----------------------------------------------
	// // drive to 1st mogo
	// driveIncremental(48);
	// wait1Msec(300);
	// extendMogo();
	// waitForPID(drivePID);
	// // grab 1st mogo and drop it off
	// intakeMogo();
	// driveIncremental(-48); // drive backwards towards start
	// waitForPID(drivePID);
	// swingTurnRight(-45);
	// waitForPID(gyroPID);
	// driveIncremental(-12);
	// waitForPID(drivePID);
	// swingTurnRight(-135);
	// waitForPID(gyroPID);
	// // tard on the pipe
	// tardDrive(127);
	// wait1Msec(1000);
	// tardDrive();
	// extendMogo();
	// // tardDrive(-60,-60,300);
	// driveIncremental(-4); // drive back enough to release mogo
	// waitForPID(drivePID);
	// intakeMogo();
  //
	// // mogo 2 - 10 pt blue
	// //----------------------------------------------
	// // tard back
	// tardDriveStraight(-127);
	// wait1Msec(2000);
	// tardDrive();
	// // driveIncremental(-24); // cross pipe
	// // waitForPID(drivePID);
	// swingTurnRight(45); // swing turn 180 degrees towards next mogo
	// extendMogo();
	// waitForPID(gyroPID);
	// driveIncremental(18);
	// waitForPID(drivePID);
	// intakeMogo(); // pick up next mogo
	// // turn around and drop off
	// pointTurn(-135);
	// waitForPID(gyroPID);
	// driveIncremental(36);
	// extendMogo();
	// driveIncremental(-5);
	// waitForPID(drivePID);
	// intakeMogo();
  //
  // // mogo 3 - 20 pt red
	// //----------------------------------------------
	// driveIncremental(-8);
	// waitForPID(drivePID);
	// pointTurn(45); // face next mogo
	// extendMogo();
	// waitForPID(gyroPID);
	// oldDrive = drivePID.input;
	// driveIncremental(100); // go all the way across the field
	// // wait for mogo halfway
	// while(DRIVE_TPI*(drivePID.input-oldDrive) <  80)
	// 	wait1Msec(drivePID.loopTime);
  //
	// intakeMogo();
	// waitForPID(drivePID);
	// // recenter and face 20 pt zone
	// swingTurnRight(90);
	// waitForPID(gyroPID);
	// driveIncremental(8);
	// waitForPID(drivePID);
	// swingTurnLeft(45);
	// waitForPID(gyroPID);
	// // tard on the pipe
	// tardDrive(127);
	// wait1Msec(1000);
	// tardDrive();
	// extendMogo();
	// // tardDrive(-60,-60,300);
	// driveIncremental(-4); // drive back enough to release mogo
	// waitForPID(drivePID);
	// intakeMogo();
  //
	// // mogo 4 - 10 pt red
	// //----------------------------------------------
	// // tard back
	// tardDriveStraight(-127);
	// wait1Msec(2000);
	// tardDrive();
	// // driveIncremental(-24); // cross pipe
	// // waitForPID(drivePID);
	// swingTurnRight(225); // swing turn 180 degrees towards next mogo
	// extendMogo();
	// waitForPID(gyroPID);
	// driveIncremental(18);
	// waitForPID(drivePID);
	// intakeMogo(); // pick up next mogo
	// // turn around and drop off
	// pointTurn(45);
	// waitForPID(gyroPID);
	// driveIncremental(36);
	// extendMogo();
	// driveIncremental(-5);
	// waitForPID(drivePID);
	// intakeMogo();
  //
	// // mogo 5 - 10 point blue
	// //----------------------------------------------
	// pointTurn(225); // face next mogo
	// extendMogo();
	// waitForPID(gyroPID);
	// oldDrive = drivePID.input;
	// driveIncremental(140); // go all the way across the field again
	// // wait for mogo halfway
	// while(DRIVE_TPI*(drivePID.input-oldDrive) <  80) wait1Msec(drivePID.loopTime);
	// intakeMogo();
	// waitForPID(drivePID);
	// extendMogo();
	// driveIncremental(-5);
	// waitForPID(drivePID);
	// intakeMogo();
  //
	// stopTask(displayTime);

}

///////////////////////////////////////////////////////////////////////////////////
// USERCONTROL
///////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	writeDebugStreamLine("usrctrl");

	// check if second controller is connected
	if (nVexRCReceiveState & vrXmit2) {
	  #include "usercontrol-2Controller.c"
	}
	else {
	  #include "usercontrol-singleController.c"
	}

}//END usercontrol()
