#pragma config(UserModel, "ports.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("vexCompetitionControl");
#pragma debuggerWindows("VexLCD");

//Main competition background code...do not modify!
// #include "Vex_Competition_Includes.c"
#warning "skills"
#include "vex.c"
#include "declarations.c"
#include "variablesForKent.c"
#include "functions.c"

///////////////////////////////////////////////////////////////////////////////////
// PRE AUTON
///////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	clearDebugStream();

	///// pre auton accelerated for testing
	// Calibrate gyro
	displayLCDCenteredString(0,"Calibrating...");
  SensorType[gyro] = sensorNone;
  wait1Msec(10);
  SensorType[gyro] = sensorGyro;
  wait1Msec(1300);
  //Adjust SensorScale to correct the scaling for your gyro
  SensorScale[gyro] = 138.5;
  clearLCDLine(0);
  clearLCDLine(1);

  initPIDVars();
	bLCDBacklight = false;
  /////

//#include "pre_auton.c"
}//END pre_auton

///////////////////////////////////////////////////////////////////////////////////
// AUTONOMOUS
///////////////////////////////////////////////////////////////////////////////////

// skills - blue side facing mogo
task autonomous(){
	writeDebugStreamLine("auton - skills");

	motor[rollers] = ROLLERS_HOLD;
  setLiftHeight(LIFT_SCHMEDIUM);
  resetDrive();
  driveIncremental(0);
  resetGyro();
  pointTurn(SensorValue[gyro]);
  startTask(liftPIDTask);
	startTask(drivePIDTask);

////////////////mogo1
	motor[mogo] = -127;
  wait1Msec(400); // 400
  driveIncremental(48);
  extendMogo();
  waitForPID(drivePID);

  intakeMogo();
  setLiftHeight(LIFT_FLOOR_HEIGHT);
  wait1Msec(300);
  motor[rollers] = ROLLERS_OUT;
	tardLift(0);

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(45);
	waitForPID(gyroPID);
	driveIncremental(-28);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);

	pointTurn(135);
	waitForPID(gyroPID);

	setLiftHeight(LIFT_SCHMEDIUM);
	motor[rollers] = 0;

	tardDrive(127);
	wait1Msec(400);
	tardDrive(60);
	wait1Msec(500);
	tardDrive(0);
	extendMogo();

	///back up
	driveIncremental(-18);
	waitForPID(drivePID);
	tardDrive(23);
	intakeMogo();
	wait1Msec(200);
	tardDrive(0);
	setGyro(135);

////////////////////////////mogo 2
	driveIncremental(-9);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(45);
	setLift(LIFT_FLOOR_HEIGHT);
	waitForPID(gyroPID);

	driveIncremental(-35);
	waitForPID(drivePID, 4000);
	wait1Msec(PID_SETTLE_TIME);
	swingTurnRight(0);
	waitForPID(gyroPID, 3000);

	tardDrive(-90);
	wait1Msec(600);
	tardDrive(0);

	setGyro(0);

	driveIncremental(2);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(-90);
	setLift(LIFT_SCHMEDIUM);
	extendMogo();
	waitForPID(gyroPID);

	driveIncremental(32);
	waitForPID(drivePID);
	intakeMogo();

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(-135);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);
	driveIncremental(-20);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(-225);
	waitForPID(gyroPID);

	tardDrive(26);
	wait1Msec(500);
	setGyro(-225);
	tardDrive(0);
	extendMogo();

///////////////////////mogo3
	driveIncremental(-12);
	waitForPID(drivePID);
	intakeMogo();

	swingTurnRight(-45); // vary this
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

	driveIncremental(15);
	waitForPID(drivePID);
	intakeMogo();

	driveIncremental(-20);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(135);
	waitForPID(gyroPID);

	tardDrive(26);
	wait1Msec(500);
	tardDrive(0);
	setGyro(135);
	extendMogo();

	driveIncremental(-12);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(315);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

////////////////////////mogo 4
	driveIncremental(70);
	waitForPID(drivePID);
	driveIncremental(50);
	intakeMogo();
	waitForPID(drivePID);

	tardDrive(26);
	wait1Msec(500);
	setGyro(315);
	tardDrive(0);
	extendMogo();

///////////////////////////mogo 5
	driveIncremental(-12);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	swingTurnLeft(180);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

	driveIncremental(44);
	waitForPID(drivePID);
	intakeMogo();

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(225);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);
	driveIncremental(-28);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);

	pointTurn(315);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

	tardDrive(127);
	wait1Msec(400);
	tardDrive(60);
	wait1Msec(500);
	tardDrive(0);
	extendMogo();

	///back up
	driveIncremental(-18);
	waitForPID(drivePID);
	tardDrive(23);
	intakeMogo();
	wait1Msec(200);
	tardDrive(0);
	setGyro(315);

//////////////////mogo 6
	driveIncremental(-9);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(225);
	setLift(LIFT_FLOOR_HEIGHT);
	waitForPID(gyroPID);

	driveIncremental(-35);
	waitForPID(drivePID, 4000);
	wait1Msec(PID_SETTLE_TIME);
	swingTurnRight(180);
	waitForPID(gyroPID, 3000);

	tardDrive(-90);
	wait1Msec(600);
	tardDrive(0);

	setGyro(0);

	driveIncremental(2);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(90);
	extendMogo();
	waitForPID(gyroPID);

	driveIncremental(32);
	waitForPID(drivePID);
	intakeMogo();

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(45);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);
	driveIncremental(-20);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(-45);
	waitForPID(gyroPID);

	tardDrive(26);
	wait1Msec(500);
	setGyro(-45);
	tardDrive(0);
	extendMogo();

/////////////////////////mogo 7
	driveIncremental(-12);
	waitForPID(drivePID);
	intakeMogo();

	swingTurnRight(135); // vary this
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

	driveIncremental(15);
	waitForPID(drivePID);
	intakeMogo();

	driveIncremental(-20);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(-45);
	waitForPID(gyroPID);

	tardDrive(26);
	wait1Msec(500);
	tardDrive(0);
	setGyro(-45);
	extendMogo();

	driveIncremental(-12);
	waitForPID(drivePID);
	wait1Msec(PID_SETTLE_TIME);
	pointTurn(135);
	waitForPID(gyroPID);
	wait1Msec(PID_SETTLE_TIME);

////////////////////mogo 8
	driveIncremental(70);
	waitForPID(drivePID);
	driveIncremental(50);
	intakeMogo();
	waitForPID(drivePID);

	tardDrive(26);
	wait1Msec(500);
	setGyro(315);
	tardDrive(0);
	extendMogo();

}

///////////////////////////////////////////////////////////////////////////////////
// USERCONTROL
///////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	writeDebugStreamLine("usrctrl");

	// check if second controller is connected
	if (nVexRCReceiveState & vrXmit2) {
	  #include "usercontrol-2Controller.c"
	}
	else {
	  #include "usercontrol-singleController.c"
	}

}//END usercontrol()
