#pragma config(UserModel, "ports.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("vexCompetitionControl");
#pragma debuggerWindows("VexLCD");

//Main competition background code...do not modify!
// #include "Vex_Competition_Includes.c"
#warning "skills"
#include "vex.c"
#include "declarations.c"
#include "variablesForKent.c"
#include "functions.c"

///////////////////////////////////////////////////////////////////////////////////
// PRE AUTON
///////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	clearDebugStream();

	///// pre auton accelerated for testing
	// Calibrate gyro
	displayLCDCenteredString(0,"Calibrating...");
  SensorType[gyro] = sensorNone;
  wait1Msec(10);
  SensorType[gyro] = sensorGyro;
  wait1Msec(1300);
  //Adjust SensorScale to correct the scaling for your gyro
  SensorScale[gyro] = 138.5;
  clearLCDLine(0);
  clearLCDLine(1);

  initPIDVars();
	bLCDBacklight = false;
  /////

//#include "pre_auton.c"
}//END pre_auton

///////////////////////////////////////////////////////////////////////////////////
// AUTONOMOUS
///////////////////////////////////////////////////////////////////////////////////

// skills - blue side facing mogo
task autonomous(){
	writeDebugStreamLine("auton - skills");

	motor[rollers] = ROLLERS_HOLD;
  setLiftHeight(LIFT_SCHMEDIUM);
  resetDrive();
  driveIncremental(0);
  resetGyro();
  pointTurn(SensorValue[gyro]);
  startTask(liftPIDTask);
	startTask(drivePIDTask);


//////////////////mogo1
	extendMogo();
	driveIncremental(36);
	waitForPID(drivePID);
	intakeMogo();
	driveIncremental(-31);
	waitForPID(drivePID);
	pointTurn(90);
	waitForPID(gyroPID);

	driveIncremental(-8);
	waitForPID(drivePID);
	pointTurn(180);
	waitForPID(gyroPID);

////dropoff
	tardDrive(127);
  wait1Msec(400);
  tardDrive(60);
  wait1Msec(500);
  tardDrive(0);
	wait1Msec(300);
	setGyro(180);
  extendMogo();

	///back up
  driveIncremental(-18);
  waitForPID(drivePID);

	//////////////////mogo2
	pointTurn(270);
	waitForPID(gyroPID);
	driveIncremental(12);
	waitForPID(drivePID);

	pointTurn(360);
	waitForPID(gyroPID);

	extendMogo();
	driveIncremental(36);
	waitForPID(drivePID);
	intakeMogo();
	driveIncremental(-31);
	waitForPID(drivePID);
	pointTurn(540);
	waitForPID(gyroPID);

	tardDrive(26);
	extendMogo();
	tardDrive(0);

	driveIncremental(-12);
	waitForPID(drivePID);

	//////////////////////mogo 3
	pointTurn(360);
	waitForPID(gyroPID);

	driveIncremental(65);
	waitForPID(drivePID);
	intakeMogo();

	driveIncremental(45);
	waitForPID(drivePID);
	pointTurn(450);
	waitForPID(gyroPID);

	driveIncremental(8);
	waitForPID(drivePID);
	pointTurn(360);
	waitForPID(gyroPID);

////dropoff
	tardDrive(127);
  wait1Msec(400);
  tardDrive(60);
  wait1Msec(500);
  tardDrive(0);
	wait1Msec(300);
	setGyro(0);
  extendMogo();

	///back up
  driveIncremental(-18);
  waitForPID(drivePID);

///////////////////////////////////mogo 4

	pointTurn(90);
	waitForPID(gyroPID);
	driveIncremental(12);
	waitForPID(drivePID);

	pointTurn(180);
	waitForPID(gyroPID);

	extendMogo();
	driveIncremental(36);
	waitForPID(drivePID);
	intakeMogo();
	driveIncremental(-31);
	waitForPID(drivePID);
	pointTurn(360);
	waitForPID(gyroPID);

	tardDrive(26);
	extendMogo();
	tardDrive(0);

	driveIncremental(-8);
	waitForPID(drivePID);

//NORMAL AUTON
	////////////////////////////////mogo 5
	pointTurn(270);
	waitForPID(gyroPID);

	driveIncremental(-6);
	waitForPID(drivePID, 2000);
	swingTurnRight(225);
	waitForPID(gyroPID, 2000);

	tardDrive(-90);
  wait1Msec(600);
  tardDrive(0);

	wait1Msec(300);
  setGyro(225);

	driveIncremental(1);
  waitForPID(drivePID);
  pointTurn(135);
  // extendMogo();
	waitForPID(gyroPID);

	driveIncremental(37);//36
  waitForPID(drivePID);
  intakeMogo();

/////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);

	pointTurn(90);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);

	pointTurn(0);
	waitForPID(gyroPID);

	tardDrive(26);
  extendMogo();
  tardDrive(0);

////////////////////////////////////////mogo 6
	driveIncremental(-8);
	waitForPID(drivePID);

	pointTurn(90);
	waitForPID(gyroPID);
//
	driveIncremental(-35);
  // extendMogo();
  waitForPID(drivePID, 4000);
  swingTurnLeft(135);
  waitForPID(gyroPID, 3000);

  tardDrive(-90);
  wait1Msec(600);
  tardDrive(0);

  wait1Msec(300);
  setGyro(135);

  driveIncremental(1);
  waitForPID(drivePID);
  pointTurn(225);
  // extendMogo();
  waitForPID(gyroPID);

  // extendMogo();
  driveIncremental(37);//36
  waitForPID(drivePID);
  intakeMogo();

////dropoff
  driveIncremental(-48);
  waitForPID(drivePID);
  swingTurnLeft(360);
  waitForPID(gyroPID);

  // setLiftHeight(LIFT_SCHMEDIUM);
  // motor[rollers] = ROLLERS_OUT;
  tardDrive(26);
  extendMogo();
  tardDrive(0);

	driveIncremental(-12);

	while(1){wait1Msec(1000);}

}

///////////////////////////////////////////////////////////////////////////////////
// USERCONTROL
///////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	writeDebugStreamLine("usrctrl");

	// check if second controller is connected
	if (nVexRCReceiveState & vrXmit2) {
	  #include "usercontrol-2Controller.c"
	}
	else {
	  #include "usercontrol-singleController.c"
	}

}//END usercontrol()
