#pragma config(UserModel, "ports.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("vexCompetitionControl");
#pragma debuggerWindows("VexLCD");

//Main competition background code...do not modify!
// #include "Vex_Competition_Includes.c"
#warning "skills"
#include "vex.c"
#include "declarations.c"
#include "variablesForKent.c"
#include "functions.c"

///////////////////////////////////////////////////////////////////////////////////
// PRE AUTON
///////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	clearDebugStream();

	///// pre auton accelerated for testing
	// Calibrate gyro
	displayLCDCenteredString(0,"Calibrating...");
  SensorType[gyro] = sensorNone;
  wait1Msec(10);
  SensorType[gyro] = sensorGyro;
  wait1Msec(1300);
  //Adjust SensorScale to correct the scaling for your gyro
  SensorScale[gyro] = 138.5;
  clearLCDLine(0);
  clearLCDLine(1);

  initPIDVars();
	bLCDBacklight = false;
  /////

	displayLCDCenteredString(0,"Red Left");

//#include "pre_auton.c"
}//END pre_auton

///////////////////////////////////////////////////////////////////////////////////
// AUTONOMOUS
///////////////////////////////////////////////////////////////////////////////////

// skills - blue side facing mogo
task autonomous(){
	writeDebugStreamLine("auton - skills");

	// initialization
	motor[rollers] = ROLLERS_HOLD;
  setLiftHeight(LIFT_SCHMEDIUM);
  resetDrive();
  // resetGyro();
	setGyro(0);
	pointTurn(0);
	driveIncremental(0);
	startTask(drivePIDTask);
  startTask(liftPIDTask);

	wait1Msec(200);

//////////////////mogo1
	motor[mogo] = -127;
	wait1Msec(400); // 400
	driveIncremental(48);
	extendMogo();
	waitForPID(drivePID);

	intakeMogo();

	////dropoff
	driveIncremental(-48);

	setLiftHeight(LIFT_FLOOR_HEIGHT);
  wait1Msec(300);
  motor[rollers] = ROLLERS_OUT;
	wait1Msec(500);
	setLiftHeight(LIFT_SCHMEDIUM);
	motor[rollers] = 0;

	waitForPID(drivePID);

	pointTurnInc(45);
	waitForPID(gyroPID);
	driveIncremental(-20);
	waitForPID(drivePID);
	pointTurnInc(90);
	waitForPID(gyroPID);

	nogoGadget();
	tardDrive(127);
  wait1Msec(400);
  tardDrive(60);
  wait1Msec(500);
  tardDrive(0);
	wait1Msec(300);
	// setGyro(135);

	///back up
  driveIncremental(-18);//18);
  waitForPID(drivePID,3000);

////////////////////////mogo 2
	pointTurnInc(-90);
	waitForPID(gyroPID);
	driveIncremental(6);
	extendMogo();
	pointTurnInc(-90);
	waitForPID(gyroPID);

	driveIncremental(32);
	waitForPID(drivePID, 4000);
	intakeMogo();
	driveIncremental(-38);//31);
	waitForPID(drivePID);

	nogoGadget();
	pointTurnInc(-180);
	wait1Msec(400);
	wait1Msec(300);
	motor[mogo] = 0;
	waitForPID(gyroPID);

	////dropoff

	// tardDrive(127);
	// wait1Msec(300);
	// tardDrive(-127);
	// wait1Msec(300);
	// tardDrive(0);

	// driveIncremental(6);
	// waitForPID(drivePID);

	// tardDrive(26);
	// extendMogo();
	// tardDrive(0);

	driveIncremental(-12);
	waitForPID(drivePID);

///////////////////////mogo 3
	pointTurnInc(-180);
	waitForPID(gyroPID);

	extendMogo();
	driveIncremental(58);
	waitForPID(drivePID);
	driveIncremental(36);
	motor[mogo] = 127;
	waitForPID(drivePID);
	motor[mogo] = 0;

	////dropoff
	// tardDrive(26);
	// extendMogo();
	// tardDrive(0);

	driveIncremental(-12);
	waitForPID(drivePID);

////////////////////////////////mogo 4
	pointTurnInc(115);
	waitForPID(gyroPID);
	driveIncremental(18);
	waitForPID(drivePID, 2000);
	pointTurnInc(20);
	waitForPID(gyroPID);
	driveIncremental(16);
	waitForPID(drivePID);

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);

	pointTurnInc(-45);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);
	pointTurnInc(-90);
	waitForPID(gyroPID);

	nogoGadget();
	tardDrive(127);
  wait1Msec(400);
  tardDrive(60);
  wait1Msec(500);
  tardDrive(0);
	wait1Msec(300);
	// setGyro(45);

	///back up
  driveIncremental(-18);
  waitForPID(drivePID);

/////////////////////mogo 5
	pointTurnInc(-115);
	waitForPID(gyroPID);
	driveIncremental(36);
	waitForPID(drivePID);
	pointTurnInc(-20);
	waitForPID(gyroPID);
	driveIncremental(12);
	intakeMogo();

	/////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);

	pointTurnInc(45);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);

	pointTurnInc(45);
	waitForPID(gyroPID);

	tardDrive(26);
  extendMogo();
  tardDrive(0);

	driveIncremental(-8);
	waitForPID(drivePID);

/////////////////////mogo 6
	swingTurnLeftInc(-180);
	motor[mogo] = 127;
	wait1Msec(400);
	motor[mogo] = -127;
	wait1Msec(400);
	waitForPID(gyroPID);

	driveIncremental(24);
	waitForPID(drivePID, 4000);
	intakeMogo();
	driveIncremental(-31);
	waitForPID(drivePID);

	pointTurnInc(180);
	waitForPID(gyroPID);

	////dropoff
	nogoGadget();

	driveIncremental(6);
	waitForPID(drivePID);

	tardDrive(26);
	extendMogo();
	tardDrive(0);

	driveIncremental(-12);
	waitForPID(drivePID);

///////////////////////////mogo 7
	pointTurnInc(-180);
	waitForPID(gyroPID);

	driveIncremental(68);
	waitForPID(drivePID);
	driveIncremental(26);
	intakeMogo();
	waitForPID(drivePID);

	////dropoff
	nogoGadget();

	tardDrive(26);
	extendMogo();
	tardDrive(0);

	driveIncremental(-12);
	waitForPID(drivePID);

/////////////////////mogo 8
	pointTurnInc(115);
	waitForPID(gyroPID);
	driveIncremental(12);
	waitForPID(drivePID, 2000);
	pointTurnInc(20);
	waitForPID(gyroPID);
	driveIncremental(24);
	waitForPID(drivePID);

	////dropoff
	driveIncremental(-48);
	waitForPID(drivePID);

	pointTurnInc(-45);
	waitForPID(gyroPID);
	driveIncremental(-12);
	waitForPID(drivePID);
	pointTurnInc(-90);
	waitForPID(gyroPID);

	tardDrive(26);
	extendMogo();
	tardDrive(0);

	driveIncremental(-8);
	waitForPID(drivePID);

////////////////////////park
	pointTurnInc(130);
	waitForPID(gyroPID);
	driveIncremental(48);


	while(1){wait1Msec(1000);}
}

///////////////////////////////////////////////////////////////////////////////////
// USERCONTROL
///////////////////////////////////////////////////////////////////////////////////

task usercontrol(){
	writeDebugStreamLine("usrctrl");

	// check if second controller is connected
	if (nVexRCReceiveState & vrXmit2) {
	  #include "usercontrol-2Controller.c"
	}
	else {
	  #include "usercontrol-singleController.c"
	}

}//END usercontrol()
