#pragma config(UserModel, "ports.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("vexCompetitionControl");
#pragma debuggerWindows("VexLCD");

//Main competition background code...do not modify!
// #include "Vex_Competition_Includes.c"
#warning "main"
#include "ledControl.c"
#include "vex.c"
#include "declarations.c"
#include "variablesForKent.c"
#include "functions.c"

///////////////////////////////////////////////////////////////////////////////////
// PRE AUTON
///////////////////////////////////////////////////////////////////////////////////

void pre_auton(){

	bDisplayCompetitionStatusOnLcd = false;
	bStopTasksBetweenModes = true;
	clearDebugStream();

	///// pre auton accelerated for testing
	// Calibrate gyro
	displayLCDCenteredString(0,"Calibrating...");
	SensorType[gyro] = sensorNone;
	wait1Msec(10);
	SensorType[gyro] = sensorGyro;
	wait1Msec(1300);
	//Adjust SensorScale to correct the scaling for your gyro
	SensorScale[gyro] = 138.5;
	clearLCDLine(0);
	clearLCDLine(1);

	initPIDVars();
	bLCDBacklight = false;
	/////

	//#include "pre_auton.c"
}//END pre_auton

///////////////////////////////////////////////////////////////////////////////////
// AUTONOMOUS
///////////////////////////////////////////////////////////////////////////////////

void sendByte(int byte1){
	sendChar(UART1, byte1);
	//writeDebugStreamline(" %i",byte1)
	//if(!bXmitComplete(UART0))  //Wait until character has been transmitted
	//wait1Msec(1);
	//writeDebugStreamline(" %i",getChar(UART1));
	//while(getChar(UART1) != byte1){
	//	sendChar(UART1, byte1);
	//}
}

task autonomous(){
	writeDebugStreamLine("auton");

	//////////////////////////////////////
	//driveIncremental(18);
	//pointTurn(90);
	//startTask(drivePIDTask);

	//while(true){wait1Msec(1000);}
	//////////////////////////////////////

	autonSelection = RED_PRIMARY;

	//startTask(displayTime);

#include "auton.c"

	stopTask(displayTime);
}

///////////////////////////////////////////////////////////////////////////////////
// USERCONTROL
///////////////////////////////////////////////////////////////////////////////////

#define WAIT_T 500

task usercontrol(){
	//	while(1){
	//		writeDebugStreamline(" %i",getChar(UART1));
	//		wait1Msec(WAIT_T);
	//}
	writeDebugStreamLine("usrctrl");
	//wait1Msec(1000);
	//sendByte(0);//garbo to clear pipes
	//sendByte(0);//garbo to clear pipes
	//sendByte(0);//garbo to clear pipes
	//sendByte(250);//fookin BENINS
	//sendByte(0);//garbo to clear pipes
	//writeDebugStreamLine("yee");


	//while(1){
	//	int x = getChar(UART1);
	//	if(x != -1){
	//	writeDebugStreamline(" %i",x);
	//	}

	//}
	//while(1){
		//writeDebugStreamline(" %i",getChar(UART1));

		//sendChar(UART1, 88);

		//sendByte(12);
		//sendByte(3);
		//sendByte(37);
		//sendByte(91);
		//sendByte(250);//fookin BENINS
		//wait1Msec(WAIT_T);

		//sendByte(1);
		//sendByte(0);
		//sendByte(0xFF);
		//sendByte(0xFF);
		//wait1Msec(WAIT_T);

		//sendByte(1);
		//sendByte(0xFF);
		//sendByte(0);
		//sendByte(0xFF);
		//wait1Msec(WAIT_T);

		//sendByte(1);
		//sendByte(0xFF);
		//sendByte(0xFF);
		//sendByte(0);
		//wait1Msec(WAIT_T);

		//sendByte(0);
		//sendByte(0);
		//sendByte(0);
		//sendByte(0);
		//wait1Msec(WAIT_T);
	//}

	//while(1){
		//for(int i = 0; i < 5; i++){
		//	sendChar(UART1, i);
		//	sendChar(UART1, 255);
		//	sendChar(UART1, 255);
		//	sendChar(UART1, 255);
		//	wait1Msec(1000);
		//}
		//wait1Msec(20);
	//}


	//setLiftHeight(700);
	//startTask(liftPIDTask);
	//setLift(60);
	//wait1Msec(1000);
	//setLift(0);

	//while(1){
	//	motor[swing] = vexRT[Ch2];
	//}
	//pointTurn(5);
	//pointTurn(180);
	//startTask(drivePIDTask);
	//waitForPID(gyroPID);
	//wait1Msec(300);

	//driveIncremental(24);


	//setGyro(0);
	//startTask(drivePIDTask);
	//pointTurnInc(90);

	//while(true){wait1Msec(1000);}
	 //for testing code above here

	 //check if second controller is connected
	 if (nVexRCReceiveState & vrXmit2) {
	 	#include "usercontrol-2Controller.c"
	 }
	 else {
	 	#include "usercontrol-singleController.c"
	 }

	 if("we haven't won yet")
	 	smackVcat();

}//END usercontrol()
